name: Keep Render App Awake

on:
  schedule:
    - cron: "*/13 * * * *"  # Ping toutes les 13 minutes

jobs:
  keep_awake:
    runs-on: ubuntu-latest
    steps:
      - name: Send request to keep app awake
        run: curl -s -o /dev/null https://projet-ra.onrender.com
